### ISSUE TITLE
Bzlmod / BCR

### ISSUE THREAD

**Issue by erikkerber** [zegl/rules_codeowners#33]
We are starting to use rules_codeowners and it's been fantastic to see this is a solved problem 🙌🏼 

It would be great to submit this to the BCR and pull it in as a Bzlmod dependency.

**Comment by zegl** [comment]
@erikkerber Hey, thanks! 🙏 I agree, submitting it to BCR would be very cool! Is this something that you’d want to help out with? Or is it easier if I do it?

**Comment by erikkerber** [comment]
I can help out with, though while I haven't done it myself I think at some point there needs to be publishing rights (?) to the author and less so a contributor.

I'll carry it as far as I can go and will reach out if I need you involved. Thanks for the quick reply 🙇🏼

**Comment by erikkerber** [comment]
At a minimum I do know rules_codeowners will need to submit stable releases. I know it's run with a `main`/SHA based system until now, so I'll leave it up to you to decide if you want to stop there or start publishing releases to be compatible with the BCR.

**Comment by zegl** [comment]
Cool! I just tagged v0.1.0 from the latest HEAD. :-)

**Comment by zegl** [comment]
@erikkerber it took some tweaks, but now we're live on the registry!

**Comment by erikkerber** [comment]
Awesome. Sorry I didn't follow through quickly here, we're using a fork of this for a hot minute while I work through some customization details and might see if they are good candidates to upstream here.

**Comment by zegl** [comment]
@erikkerber No worries, PRs are very welcome :-)
